---

- name: restart-nginx
  service: name=nginx state=restarted

- name: validate-nginx-configuration
  command: nginx -t -c /etc/nginx/nginx.conf
  changed_when: False

- name: reload-nginx
  service: name=nginx state=reloaded

- name: restart-app
  community.docker.docker_compose:
    build: no
    project_src: "{{ APP_DIR }}"
    recreate: always
    restarted: yes
  register: restart_app_output

- name: restart-app-api
  community.docker.docker_compose:
    build: no
    project_src: "{{ APP_DIR }}"
    services:
        - api
        - api-docs
    restarted: true
    state: present

- name: output from restart-app handler
  debug:
    msg: "{{ restart_app_output }}"

- name: restart-app
  community.docker.docker_compose:
    build: no
    project_src: "{{ APP_DIR }}"
    services:
        - api-docs
        - elasticsearch
        - db
        - api
    restarted: true
    state: present
